### ISSUE TITLE
Add example SEDCMD to mask data in position of passwords

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#17]
The Sysmon data set picks up a lot of passwords in CommandLine and ParentCommandLine fields.   It is very difficult to define a regular expression which identifies passwords with 100% accuracy.  Instead, a Splunk admin can implement a strategy of replacing text in known positions of passwords.   Add an example of use of SEDCMD in props.conf to mask data in known positions of passwords.

**Comment by MikeKemmerer** [comment]
I don't think this should be in the default settings of the app. You might
want your analysts to know what passwords someone might be using to run
scripts, as it could assist with attribution, response, and legal action in
the even of misuse or fraud.

I don't mean to get off on a rant here, but...
Instead of masking the passwords used in your scheduled tasks, etc. , you
should probably find a better way of running your scripts. Once an
adversary pops one of your boxes, they'll get that password when they
enumerate scheduled tasks or when they search through the logs to find if
the sysadmins are that sloppy.

Also, I hope that the password you're concerned about is not the local
admin password that's used throughout the environment. Because that's day
one stuff.

**Comment by dstaulcu** [comment]
Different organizations will have different policies on how to treat sensitive data in Splunk.

For those organizations, which don’t want their Splunk analysts to come across it so easy, it would be nice to have an example of how to handle the situation.   Perhaps a compromise would be to include an example but to have it commented out by default.

I don’t foresee a single entry (regular expression) which would handle all passwords, so providing a sample transform is mostly about getting folks started.

David

**Comment by daveherrald** [comment]
Good discussion. Can't thank you both enough for your ongoing contributions and discussion. 

Every org and situation will be different. We'd never be able to include such config directly in the add-on by default, however we could certainly add some directions in the README to serve as a jumping off point for those interested. We could also refer to some existing documentation on the broader topic of anonymizing data in Splunk. Finally we could even write a Splunk blog post on this topic showing how we modified stock Sysmon TA per instructions in README to attempt to mask passwords.

@dstaulcu can you propose appropriate changes to the README?

**Comment by dstaulcu** [comment]
Sounds good.

Problem is only going to get worse as folks adapt to this<https://www.microsoft.com/en-us/download/details.aspx?id=52630>.  Search for “command line”.  I like the idea of providing a per-source type (Sysmon, Security log, etc) approach and then let the community contribute to a library of knows.

**Comment by MikeKemmerer** [comment]
This is where the MITRE CAR data model (
https://car.mitre.org/wiki/Data_Model) might come in handy for inspiration.
As long as you have a specific action on an object (like process create)
you just need to alias the field names to fit the CIM or your own data
model and develop all of your analytics to your data model. It doesn't
matter what your sources are. Whether it's security logs, sysmon logs, or
carbon black logs, your analytics will work and you can share then with
others.


On Dec 14, 2016 7:37 PM, "dstaulcu" <notifications@github.com> wrote:

Sounds good.

Problem is only going to get worse as folks adapt to this<
https://www.microsoft.com/en-us/download/details.aspx?id=52630>. Search for
“command line”. I like the idea of providing a per-source type (Sysmon,
Security log, etc) approach and then let the community contribute to a
library of knows.
